import jsPDF from "jspdf";
import type { AcordFormDefinition } from "./acord-forms";
import { FIELD_POSITION_MAP } from "./acord-field-positions";
import { formatUSD, CURRENCY_FIELDS } from "./acord-autofill";

/**
 * Load an image from a URL and return as base64 data URL
 */
async function loadImageAsBase64(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      if (!ctx) { reject(new Error("No canvas context")); return; }
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/jpeg", 0.92));
    };
    img.onerror = () => reject(new Error(`Failed to load image: ${url}`));
    img.src = url;
  });
}

/** Format a value for PDF overlay display */
function formatFieldValuePkg(key: string, val: any): string {
  if (val === null || val === undefined || val === "") return "";
  const s = String(val);
  if (s === "true") return "✓";
  if (s === "false") return "";
  if (CURRENCY_FIELDS.has(key)) return formatUSD(s);
  // Format dates as MM/DD/YYYY
  const isoMatch = s.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (isoMatch && (key.includes("date") || key.includes("eff_") || key.includes("exp_"))) {
    return `${isoMatch[2]}/${isoMatch[3]}/${isoMatch[1]}`;
  }
  return s;
}

type SubmissionPackageOptions = {
  companyName: string;
  narrative: string;
  agencyName?: string;
  producerName?: string;
  coverageLines: string[];
  forms: { form: AcordFormDefinition; data: Record<string, any> }[];
  effectiveDate?: string;
};

/**
 * Generate a single bundled PDF containing:
 * 1. Professional cover page
 * 2. Narrative / business summary page
 * 3. All selected ACORD form page images (compliant template format)
 */
export async function generateSubmissionPackage(opts: SubmissionPackageOptions): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const margin = 50;
  const cw = pw - margin * 2;

  // ─── Page 1: Cover Page ───────────────────────────────
  doc.setFillColor(20, 45, 90);
  doc.rect(0, 0, pw, 180, "F");

  doc.setTextColor(255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Insurance Submission", margin, 80);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Carrier-Ready Application Package", margin, 105);

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(10);
  doc.text(today, margin, 135);

  doc.setTextColor(20, 45, 90);
  let y = 220;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120);
  doc.text("NAMED INSURED", margin, y);
  y += 18;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(opts.companyName || "—", margin, y);
  y += 35;

  const infoRows: [string, string][] = [];
  if (opts.agencyName) infoRows.push(["AGENCY", opts.agencyName]);
  if (opts.producerName) infoRows.push(["PRODUCER", opts.producerName]);
  if (opts.effectiveDate) infoRows.push(["EFFECTIVE DATE", opts.effectiveDate]);
  if (opts.coverageLines.length > 0)
    infoRows.push(["LINES OF COVERAGE", opts.coverageLines.join(", ")]);

  for (const [label, value] of infoRows) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120);
    doc.text(label, margin, y);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    doc.text(value, margin + 130, y);
    y += 22;
  }

  y += 15;
  doc.setDrawColor(200);
  doc.line(margin, y, pw - margin, y);
  y += 20;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120);
  doc.text("FORMS INCLUDED", margin, y);
  y += 16;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0);
  for (const { form } of opts.forms) {
    doc.text(`• ${form.name} — ${form.fullName}`, margin + 10, y);
    y += 16;
  }

  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.text("Generated by AURA Risk Group", margin, ph - 40);

  // ─── Page 2: Narrative (if provided) ──────────────────
  if (opts.narrative.trim()) {
    doc.addPage();
    y = margin;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 45, 90);
    doc.text("Business Narrative", margin, y);
    y += 8;
    doc.setDrawColor(20, 45, 90);
    doc.line(margin, y, pw - margin, y);
    y += 20;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40);

    const narrativeLines = doc.splitTextToSize(opts.narrative, cw);
    for (const line of narrativeLines) {
      if (y + 14 > ph - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 14;
    }
  }

  // ─── Remaining Pages: Embed actual ACORD form page images ─────────────────
  for (const { form, data } of opts.forms) {
    if (form.pages && form.pages.length > 0) {
      const positions = FIELD_POSITION_MAP[form.id] || {};
      for (let i = 0; i < form.pages.length; i++) {
        doc.addPage();
        try {
          const imgData = await loadImageAsBase64(form.pages[i]);
          doc.addImage(imgData, "JPEG", 0, 0, pw, ph);
        } catch (err) {
          console.warn(`Could not load page image ${form.pages[i]}:`, err);
          doc.setFontSize(14);
          doc.setTextColor(150);
          doc.text(`${form.name} — Page ${i + 1}`, pw / 2, ph / 2, { align: "center" });
          doc.setTextColor(0);
        }
      }

      // Overlay field data on this form's pages
      const formStartPage = doc.internal.pages.length - form.pages.length;
      doc.setTextColor(0, 0, 140);
      for (const [key, pos] of Object.entries(positions)) {
        const raw = data[key];
        if (raw === undefined || raw === null || raw === "") continue;
        const display = formatFieldValuePkg(key, raw);
        if (!display) continue;
        if (pos.page >= form.pages.length) continue;

        doc.setPage(formStartPage + pos.page);
        const fontSize = pos.fontSize || 8;
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", "normal");

        if (pos.checkbox) {
          if (display === "✓" || raw === true || raw === "Yes") {
            doc.setFontSize(12);
            doc.text("✓", pos.x, pos.y);
          }
        } else {
          const maxW = pos.maxWidth || 200;
          const lines = doc.splitTextToSize(display, maxW);
          doc.text(lines, pos.x, pos.y);
        }
      }
      doc.setTextColor(0);
    }
  }

  return doc;
}
