import jsPDF from "jspdf";
import type { AcordFormDefinition } from "./acord-forms";

type SubmissionPackageOptions = {
  companyName: string;
  narrative: string;
  agencyName?: string;
  producerName?: string;
  coverageLines: string[];
  forms: { form: AcordFormDefinition; data: Record<string, any> }[];
  effectiveDate?: string;
};

/**
 * Generate a single bundled PDF containing:
 * 1. Professional cover page
 * 2. Narrative / business summary page
 * 3. All selected ACORD forms
 */
export function generateSubmissionPackage(opts: SubmissionPackageOptions): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const margin = 50;
  const cw = pw - margin * 2;

  // ─── Page 1: Cover Page ───────────────────────────────
  // Background accent bar
  doc.setFillColor(20, 45, 90);
  doc.rect(0, 0, pw, 180, "F");

  // Title area
  doc.setTextColor(255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Insurance Submission", margin, 80);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Carrier-Ready Application Package", margin, 105);

  // Date
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(10);
  doc.text(today, margin, 135);

  // Company name block
  doc.setTextColor(20, 45, 90);
  let y = 220;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120);
  doc.text("NAMED INSURED", margin, y);
  y += 18;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(opts.companyName || "—", margin, y);
  y += 35;

  // Info grid
  const infoRows: [string, string][] = [];
  if (opts.agencyName) infoRows.push(["AGENCY", opts.agencyName]);
  if (opts.producerName) infoRows.push(["PRODUCER", opts.producerName]);
  if (opts.effectiveDate) infoRows.push(["EFFECTIVE DATE", opts.effectiveDate]);
  if (opts.coverageLines.length > 0)
    infoRows.push(["LINES OF COVERAGE", opts.coverageLines.join(", ")]);

  for (const [label, value] of infoRows) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120);
    doc.text(label, margin, y);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    doc.text(value, margin + 130, y);
    y += 22;
  }

  // Forms included
  y += 15;
  doc.setDrawColor(200);
  doc.line(margin, y, pw - margin, y);
  y += 20;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120);
  doc.text("FORMS INCLUDED", margin, y);
  y += 16;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0);
  for (const { form } of opts.forms) {
    doc.text(`• ${form.name} — ${form.fullName}`, margin + 10, y);
    y += 16;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.text("Generated by EPOCH Risk Group", margin, ph - 40);

  // ─── Page 2: Narrative (if provided) ──────────────────
  if (opts.narrative.trim()) {
    doc.addPage();
    y = margin;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 45, 90);
    doc.text("Business Narrative", margin, y);
    y += 8;
    doc.setDrawColor(20, 45, 90);
    doc.line(margin, y, pw - margin, y);
    y += 20;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40);

    const narrativeLines = doc.splitTextToSize(opts.narrative, cw);
    for (const line of narrativeLines) {
      if (y + 14 > ph - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 14;
    }
  }

  // ─── Remaining Pages: Each ACORD Form ─────────────────
  for (const { form, data } of opts.forms) {
    doc.addPage();
    y = margin;

    // Form header
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text(form.name, margin, y);
    y += 18;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(form.fullName, margin, y);
    y += 14;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`Generated ${today}`, margin, y);
    doc.setTextColor(0);
    y += 20;
    doc.setDrawColor(200);
    doc.line(margin, y, pw - margin, y);
    y += 15;

    // Group fields by section
    const sections: Record<string, typeof form.fields> = {};
    for (const field of form.fields) {
      if (!sections[field.section]) sections[field.section] = [];
      sections[field.section].push(field);
    }

    for (const [sectionName, fields] of Object.entries(sections)) {
      if (y + 40 > ph - margin) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 60, 120);
      doc.text(sectionName.toUpperCase(), margin, y);
      y += 4;
      doc.setDrawColor(30, 60, 120);
      doc.line(margin, y, pw - margin, y);
      doc.setTextColor(0);
      doc.setDrawColor(200);
      y += 14;

      for (const field of fields) {
        if (y + 32 > ph - margin) {
          doc.addPage();
          y = margin;
        }

        const value = data[field.key];
        const displayValue = value
          ? Array.isArray(value)
            ? value.join(", ")
            : String(value)
          : "";

        // Label
        doc.setFontSize(7);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(100);
        doc.text(field.label.toUpperCase(), margin, y);
        y += 10;

        // Value
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0);

        if (field.type === "textarea" && displayValue.length > 80) {
          const lines = doc.splitTextToSize(displayValue, cw);
          for (const line of lines) {
            if (y + 14 > ph - margin) {
              doc.addPage();
              y = margin;
            }
            doc.text(line, margin, y);
            y += 13;
          }
        } else {
          doc.text(displayValue || "—", margin, y);
          y += 13;
        }

        doc.setDrawColor(230);
        doc.line(margin, y, pw - margin, y);
        y += 10;
      }
      y += 6;
    }
  }

  return doc;
}
