import {
  Heart, RefreshCw, UserPlus, Lightbulb, Calendar, Zap,
  Shield, DollarSign, TrendingUp, Users, Mail, BarChart3, Gift, Network,
} from "lucide-react";

export interface SpotlightTemplate {
  id: string;
  name: string;
  tagline: string;
  contentType: string; // matches FLYER_TYPES value
  icon: typeof Heart;
  thumbnailBg: string; // HSL or hex
  prompt: string;
  title: string;
  bullets: string[];
  cta: string;
  disclaimer: string;
  // Extended fields from Canva research
  vertical?: string[] | null;
  category?: string;
  format?: string;
  colors?: string[];
  canvaUrl?: string;
  thumbnailUrl?: string;
}

export const SPOTLIGHT_TEMPLATES: SpotlightTemplate[] = [
  // ── ORIGINAL 6 ──────────────────────────────────────────────────────────────
  {
    id: "referral-ask",
    name: "Referral Ask",
    tagline: "Turn your network into your pipeline",
    contentType: "social",
    icon: Heart,
    thumbnailBg: "hsl(340 60% 45%)",
    prompt: "Create a warm, professional social media post asking my network to refer anyone who may need insurance coverage. The tone should be grateful and relationship-driven, not salesy. Mention that I make the process simple and that referrals mean a lot to my practice.",
    title: "Your Referral Means the World",
    bullets: [
      "I help individuals, families, and businesses get the right coverage",
      "Quick, no-pressure conversations — I do the heavy lifting",
      "Your referral means the world to my practice",
      "Happy to return the favor — let's connect",
    ],
    cta: "Send me a referral",
    disclaimer: "",
  },
  {
    id: "renewal-reminder",
    name: "Renewal Reminder",
    tagline: "Keep clients before someone else does",
    contentType: "announcement",
    icon: RefreshCw,
    thumbnailBg: "hsl(200 60% 42%)",
    prompt: "Create a professional announcement reminding clients that policy renewals are coming up. Emphasize the value of reviewing coverage annually, protecting against gaps, and that I am here to make the renewal process easy.",
    title: "It's Renewal Season — Let's Review Your Coverage",
    bullets: [
      "Coverage needs change — annual reviews catch gaps",
      "Rate shopping across carriers to get you the best value",
      "Renewals processed quickly with minimal paperwork",
      "Reach out now before your policy lapses",
    ],
    cta: "Schedule your review today",
    disclaimer: "Coverage subject to underwriting approval. Contact us for details.",
  },
  {
    id: "new-client-welcome",
    name: "New Client Welcome",
    tagline: "Celebrate the relationship from day one",
    contentType: "announcement",
    icon: UserPlus,
    thumbnailBg: "hsl(140 40% 38%)",
    prompt: "Create a warm welcome post celebrating a new client relationship. Express gratitude for their trust, briefly highlight the service experience they can expect, and invite their friends and family to reach out.",
    title: "Welcome Aboard — We're Proud to Protect You",
    bullets: [
      "Proud to protect another client and their family",
      "You can count on us for fast answers and real advocacy",
      "Coverage questions? We are always one call away",
      "Tell your friends — we would love to help them too",
    ],
    cta: "Welcome aboard",
    disclaimer: "",
  },
  {
    id: "risk-tip",
    name: "Risk Tip of the Week",
    tagline: "Educate your audience, build your authority",
    contentType: "educational",
    icon: Lightbulb,
    thumbnailBg: "hsl(45 70% 45%)",
    prompt: "Create an educational social media graphic with a risk management tip for business owners. Focus on one specific actionable tip related to liability, cyber security, commercial property, workers compensation, or business continuity. Position it as expert advice from a trusted insurance professional.",
    title: "Risk Tip: Is Your Cyber Coverage Enough?",
    bullets: [
      "Most business owners underestimate their cyber exposure",
      "One data breach can cost more than your annual premium",
      "Cyber liability insurance covers breach response costs",
      "Ask your agent to review your current cyber limits",
    ],
    cta: "Get a free coverage review",
    disclaimer: "For informational purposes only. Consult a licensed insurance professional.",
  },
  {
    id: "event-invite",
    name: "Event Invite",
    tagline: "Fill your next seminar, lunch, or mixer",
    contentType: "event",
    icon: Calendar,
    thumbnailBg: "hsl(270 45% 45%)",
    prompt: "Create a professional event invitation flyer for a business networking event or educational seminar hosted by an insurance professional. The tone should be inviting and professional with a clear RSVP call to action.",
    title: "You're Invited — Business Networking Event",
    bullets: [
      "Connect with local business owners and professionals",
      "Learn actionable strategies to protect your business",
      "Complimentary lunch and refreshments provided",
      "Limited spots available — reserve yours today",
    ],
    cta: "RSVP Now — Space Is Limited",
    disclaimer: "Event details subject to change. Contact us for accessibility accommodations.",
  },
  {
    id: "seasonal-promo",
    name: "Seasonal Promotion",
    tagline: "Drive urgency with a timely offer",
    contentType: "promotion",
    icon: Zap,
    thumbnailBg: "hsl(15 70% 48%)",
    prompt: "Create a promotional social media graphic for a seasonal insurance offer. Create urgency without being aggressive. Highlight the limited-time nature of the offer and a clear benefit of acting now.",
    title: "Limited Time — Lock In Your Rate Today",
    bullets: [
      "Rates are competitive right now — lock yours in before they change",
      "Quick 15-minute review could save you hundreds",
      "New carrier options available for your industry",
      "Limited-time offer — do not wait until renewal",
    ],
    cta: "Get a free quote today",
    disclaimer: "Offer subject to underwriting approval and eligibility requirements.",
  },

  // ── 20 NEW CANVA-INSPIRED TEMPLATES ─────────────────────────────────────────

  // --- FLYERS ---
  {
    id: "family-insurance-flyer",
    name: "Family Insurance Flyer",
    tagline: "Protect every member of the family",
    contentType: "promotion",
    icon: Shield,
    thumbnailBg: "#1A3E7A",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#1A3E7A", "#FFFFFF", "#4A90D9", "#E8F0FE"],
    vertical: ["personal_lines", "life_insurance"],
    canvaUrl: "https://www.canva.com/templates/EAGw8o0ifV8-blue-and-white-modern-family-insurance-flyer/",
    thumbnailUrl: "https://marketplace.canva.com/EAGw8o0ifV8/1/0/566w/canva-blue-and-white-modern-family-insurance-flyer-wHfLUrGJRLw.jpg",
    prompt: "Create a compelling family insurance promotion flyer highlighting peace of mind, comprehensive coverage for health, life, and emergencies, and a clear call-to-action to get a customized plan.",
    title: "Secure Your Family's Future",
    bullets: [
      "Comprehensive coverage for health, life, and emergencies",
      "Peace of mind knowing every family member is protected",
      "Affordable plans tailored to your family's needs",
      "Quick, personalized quotes — no pressure",
    ],
    cta: "Get a Customized Plan Today",
    disclaimer: "Coverage subject to underwriting approval.",
  },
  {
    id: "insurance-agency-service-flyer",
    name: "Insurance Agency Service Flyer",
    tagline: "Market your full range of services",
    contentType: "promotion",
    icon: Shield,
    thumbnailBg: "#0F2B6B",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#0F2B6B", "#1E5FBF", "#3A9EDB", "#FFFFFF"],
    vertical: ["commercial_lines", "personal_lines"],
    canvaUrl: "https://www.canva.com/templates/EAG_Grcd4OM-blue-modern-insurance-service-flyer/",
    thumbnailUrl: "https://marketplace.canva.com/EAG_Grcd4OM/1/0/566w/canva-blue-modern-insurance-service-flyer-q2GGyOnjzww.jpg",
    prompt: "Create a professional insurance agency service flyer listing all coverage lines offered. Emphasize integrity, long-term protection, and claim assistance. Include a contact section with phone and website.",
    title: "Your Trusted Insurance Agency",
    bullets: [
      "Claim assistance — we advocate for you when it matters most",
      "Retirement & pension insurance planning",
      "Education, personal accident, and life coverage",
      "One agency for all your protection needs",
    ],
    cta: "Contact Us Today",
    disclaimer: "Coverage subject to underwriting approval and eligibility requirements.",
  },
  {
    id: "life-insurance-flyer-teal",
    name: "Life Insurance Flyer — Teal",
    tagline: "Educate prospects on life coverage options",
    contentType: "promotion",
    icon: Shield,
    thumbnailBg: "#006B6B",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#006B6B", "#00A878", "#FFFFFF", "#2C2C2C"],
    vertical: ["life_insurance"],
    canvaUrl: "https://www.canva.com/templates/EAG4Elro-c4-teal-and-white-modern-life-insurance-flyer-portrait/",
    thumbnailUrl: "https://marketplace.canva.com/EAG4Elro-c4/1/0/566w/canva-teal-and-white-modern-life-insurance-flyer-portrait-icMvJCbwrzc.jpg",
    prompt: "Create an educational life insurance flyer covering available plan types: retirement and pension plans, accidental death benefits, critical illness coverage, group life, and child life insurance. Tone: informative and reassuring.",
    title: "Life Insurance — Plans Built Around You",
    bullets: [
      "Retirement & pension plans to protect your future income",
      "Accidental death and critical illness coverage",
      "Group life insurance for businesses and associations",
      "Child life insurance — protect them from day one",
    ],
    cta: "Get More Info Today",
    disclaimer: "Coverage subject to underwriting approval.",
  },
  {
    id: "life-insurance-flyer-red",
    name: "Life Insurance Flyer — Red",
    tagline: "Drive leads with bold financial security messaging",
    contentType: "promotion",
    icon: Shield,
    thumbnailBg: "#C0392B",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#C0392B", "#FFFFFF", "#2C2C2C", "#F5F5F5"],
    vertical: ["life_insurance", "personal_lines"],
    canvaUrl: "https://www.canva.com/templates/EAG5Al-KW3c-red-and-white-modern-life-insurance-flyer/",
    thumbnailUrl: "https://marketplace.canva.com/EAG5Al-KW3c/1/0/566w/canva-red-and-white-modern-life-insurance-flyer-wnfTU3bSXZY.jpg",
    prompt: "Create a bold, action-driven life insurance flyer communicating financial security for the whole family. Emphasize legacy protection and urgency to act now before it is too late.",
    title: "Start Your Life Insurance Today",
    bullets: [
      "Covers final expenses so your family isn't burdened",
      "Secures your children's future no matter what",
      "Protects your legacy and everything you've built",
      "Builds financial security your family can count on",
    ],
    cta: "Get Covered Now",
    disclaimer: "Coverage subject to underwriting approval.",
  },
  {
    id: "financial-advisor-flyer-clean",
    name: "Financial Advisor Flyer",
    tagline: "Attract wealth management clients",
    contentType: "promotion",
    icon: DollarSign,
    thumbnailBg: "#B8860B",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#FFFFFF", "#F5EED8", "#2C2C2C", "#B8860B"],
    vertical: ["financial_advisor"],
    canvaUrl: "https://www.canva.com/templates/EAE7NxmBsO0-white-clean-financial-advisor-flyer/",
    thumbnailUrl: "https://marketplace.canva.com/EAE7NxmBsO0/1/0/566w/canva-white-clean-financial-advisor-flyer-5DhGXWfi6pQ.jpg",
    prompt: "Create a professional, clean financial advisor flyer for attracting new wealth management and financial planning clients. Emphasize expertise, personalized service, and a clear path to getting started.",
    title: "We'll Manage Your Finances Better",
    bullets: [
      "Personalized investment strategies built around your goals",
      "Retirement planning, tax optimization, and wealth preservation",
      "Transparent fee structure — no hidden surprises",
      "Trusted by hundreds of businesses and families",
    ],
    cta: "Get Started Today",
    disclaimer: "Investment advice provided by licensed professionals. Past performance is not indicative of future results.",
  },
  {
    id: "life-insurance-flyer-pink",
    name: "Life Insurance Flyer — Pink",
    tagline: "Target families with warm, illustrated messaging",
    contentType: "promotion",
    icon: Heart,
    thumbnailBg: "#E91E8C",
    category: "flyer",
    format: "8.5 × 11 in",
    colors: ["#F48FB1", "#FFFFFF", "#E91E8C", "#FCE4EC"],
    vertical: ["life_insurance", "healthcare"],
    canvaUrl: "https://www.canva.com/templates/EAG6EH5eQc0-pink-and-white-illustrated-life-insurance-flyer-portrait/",
    thumbnailUrl: "https://marketplace.canva.com/EAG6EH5eQc0/1/0/566w/canva-pink-and-white-illustrated-life-insurance-flyer-portrait-KfkhC3-KVx4.jpg",
    prompt: "Create a warm, illustrated life insurance flyer targeting families and female decision-makers. Emphasize peace of mind, protection for loved ones, and the ease of getting covered. Tone should be caring and approachable.",
    title: "Life Insurance That Gives You Peace of Mind",
    bullets: [
      "Protect the people you love most with the right coverage",
      "Affordable plans designed for families at every stage",
      "Quick and easy — get covered in as little as one day",
      "Supplemental coverage options for healthcare professionals",
    ],
    cta: "Book Your Free Consultation",
    disclaimer: "Coverage subject to underwriting approval.",
  },

  // --- INSTAGRAM POSTS ---
  {
    id: "financial-advisor-instagram-bw",
    name: "Financial Advisor — Instagram (B&W)",
    tagline: "Minimal, premium social media presence",
    contentType: "social",
    icon: TrendingUp,
    thumbnailBg: "#1A1A1A",
    category: "instagram",
    format: "1080 × 1080 px",
    colors: ["#F7F5F0", "#1A1A1A", "#D4AF37", "#4A4A4A"],
    vertical: ["financial_advisor"],
    canvaUrl: "https://www.canva.com/templates/EAGle1UPnLg-white-and-black-modern-financial-advisor-services-instagram-post/",
    thumbnailUrl: "https://marketplace.canva.com/EAGle1UPnLg/1/0/320w/canva-white-and-black-modern-financial-advisor-services-instagram-post-3utFl-asX3Y.jpg",
    prompt: "Create a clean, minimal Instagram post promoting financial advisor services. Focus on wealth growth, expert guidance, and credibility. The tone should be sophisticated and authoritative.",
    title: "Grow Your Wealth with Expert Guidance",
    bullets: [
      "Investment strategy built around your unique goals",
      "Portfolio management and retirement planning",
      "Fiduciary advice — your interests always come first",
      "Schedule a complimentary discovery call today",
    ],
    cta: "Learn More",
    disclaimer: "",
  },
  {
    id: "financial-advisor-instagram-blue",
    name: "Financial Advisor — Instagram (Blue)",
    tagline: "Build brand awareness on Instagram and LinkedIn",
    contentType: "social",
    icon: DollarSign,
    thumbnailBg: "#1A3A6E",
    category: "instagram",
    format: "1080 × 1080 px",
    colors: ["#1A3A6E", "#FFFFFF", "#4A90D9", "#E8F4FD"],
    vertical: ["financial_advisor"],
    canvaUrl: "https://www.canva.com/templates/EAGle0fXEwE-blue-and-white-simple-financial-advisor-services-instagram-post/",
    thumbnailUrl: "https://marketplace.canva.com/EAGle0fXEwE/1/0/320w/canva-blue-and-white-simple-financial-advisor-services-instagram-post-Op_Mbouqw_k.jpg",
    prompt: "Create a professional blue-themed Instagram post showcasing financial advisor services. Use a split-panel design with service list on one side and professional branding on the other.",
    title: "Financial Advisor Services",
    bullets: [
      "Retirement and wealth planning for individuals and businesses",
      "Tax-efficient investment strategies",
      "Insurance and risk management consulting",
      "Long-term relationships built on trust and results",
    ],
    cta: "Connect With Me",
    disclaimer: "",
  },
  {
    id: "financial-advisor-instagram-green",
    name: "Financial Advisor — Instagram (Green)",
    tagline: "Premium positioning for high-net-worth targeting",
    contentType: "social",
    icon: TrendingUp,
    thumbnailBg: "#1B4332",
    category: "instagram",
    format: "1080 × 1080 px",
    colors: ["#1B4332", "#FFFFFF", "#40916C", "#D4EDDA"],
    vertical: ["financial_advisor"],
    canvaUrl: "https://www.canva.com/templates/EAGa7kn-lXc-dark-green-and-white-financial-advisor-services-instagram-post/",
    thumbnailUrl: "https://marketplace.canva.com/EAGa7kn-lXc/1/0/400w/canva-dark-green-and-white-financial-advisor-services-instagram-post-ko5pKxIw474.jpg",
    prompt: "Create a premium dark-green Instagram post for a financial advisor targeting high-net-worth individuals and business owners. Emphasize trust, expertise, and results.",
    title: "Your Trusted Financial Advisor",
    bullets: [
      "Proven strategies to grow and protect your wealth",
      "Personalized service — not a cookie-cutter approach",
      "Business succession and estate planning expertise",
      "Over a decade of results for families and founders",
    ],
    cta: "Schedule a Private Consultation",
    disclaimer: "",
  },
  {
    id: "networking-steps-infographic",
    name: "Networking Steps — Instagram Infographic",
    tagline: "Educate your audience and build authority",
    contentType: "educational",
    icon: Network,
    thumbnailBg: "#2C3E50",
    category: "instagram",
    format: "1080 × 1080 px",
    colors: ["#2C3E50", "#E74C3C", "#3498DB", "#ECF0F1"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAGzwU-V-C4-professional-networking-steps-infographic-instagram/",
    thumbnailUrl: "https://marketplace.canva.com/EAGzwU-V-C4/1/0/320w/canva-professional-networking-steps-infographic-instagram-zPI88fiiG48.jpg",
    prompt: "Create an Instagram infographic outlining the key steps to professional networking for insurance agents, financial advisors, and service professionals. Use numbered steps with icons and brief descriptions.",
    title: "5 Steps to Professional Networking",
    bullets: [
      "Step 1: Define your ideal connection and target them intentionally",
      "Step 2: Attend industry events and follow up within 24 hours",
      "Step 3: Add value first — share insights and make introductions",
      "Step 4: Use LinkedIn and CRM tools to stay top-of-mind",
      "Step 5: Build a referral culture through consistent relationships",
    ],
    cta: "Follow for more networking tips",
    disclaimer: "",
  },

  // --- EMAIL NEWSLETTERS ---
  {
    id: "newsletter-email-header",
    name: "Newsletter Email Header",
    tagline: "Brand every email with a professional header",
    contentType: "announcement",
    icon: Mail,
    thumbnailBg: "#1A3E7A",
    category: "newsletter",
    format: "600 × 200 px",
    colors: ["#1A3E7A", "#4A90D9", "#FFFFFF", "#F0F4FF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAFzUk6uSpk-blue-and-white-professional-newsletter-email-header/",
    thumbnailUrl: "https://marketplace.canva.com/EAFzUk6uSpk/1/0/400w/canva-blue-and-white-professional-newsletter-email-header-HGb5Xwjxx7U.jpg",
    prompt: "Create a professional email newsletter header banner for an insurance or financial services professional. Include a company logo area, newsletter title, and an inviting tagline.",
    title: "Monthly Client Newsletter",
    bullets: [
      "Market updates and coverage tips delivered monthly",
      "Exclusive offers for existing clients and referrals",
      "Industry news relevant to your business",
      "Quick access to your account and contact info",
    ],
    cta: "Subscribe Now",
    disclaimer: "",
  },
  {
    id: "business-newsletter-dark-blue",
    name: "Business Newsletter — Dark Blue",
    tagline: "Professional email marketing for client retention",
    contentType: "announcement",
    icon: Mail,
    thumbnailBg: "#0D0D0D",
    category: "newsletter",
    format: "660 × 1500 px",
    colors: ["#0D0D0D", "#1A3E7A", "#4A90D9", "#FFFFFF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAGWT_VbOgs-black-and-blue-modern-business-company-email-newsletter/",
    thumbnailUrl: "https://marketplace.canva.com/EAGWT_VbOgs/1/0/566w/canva-black-and-blue-modern-business-company-email-newsletter-jngeu31PvdU.jpg",
    prompt: "Create a monthly business email newsletter for an insurance or financial services firm. Include a bold headline news section, a leading solutions feature, and a closing CTA. Tone: professional and informative.",
    title: "Transforming Business Today",
    bullets: [
      "Top industry news and market updates this month",
      "Leading solutions helping clients protect what matters",
      "Case study spotlight: how we saved a client thousands",
      "Upcoming events, webinars, and renewal reminders",
    ],
    cta: "Read This Month's Edition",
    disclaimer: "You are receiving this because you are a valued client or subscriber.",
  },
  {
    id: "business-newsletter-grey",
    name: "Business Newsletter — Grey",
    tagline: "Sophisticated monochrome client communications",
    contentType: "announcement",
    icon: Mail,
    thumbnailBg: "#1A1A1A",
    category: "newsletter",
    format: "660 × 1500 px",
    colors: ["#1A1A1A", "#4A4A4A", "#E5E5E5", "#FFFFFF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAGWT7FdhOk-black-and-grey-modern-business-company-email-newsletter/",
    thumbnailUrl: "https://marketplace.canva.com/EAGWT7FdhOk/1/0/566w/canva-black-and-grey-modern-business-company-email-newsletter-LWhdkbTFSQo.jpg",
    prompt: "Create a sophisticated grey-toned business newsletter for a B2B insurance agency or financial advisory firm. Focus on professionalism, industry authority, and consistent client communication.",
    title: "Your Monthly Business Intelligence Brief",
    bullets: [
      "Key regulatory changes affecting your coverage this quarter",
      "Rate environment update — what to expect at renewal",
      "Risk management spotlight for your industry",
      "Client services reminder and account review offer",
    ],
    cta: "View Full Newsletter",
    disclaimer: "You are receiving this because you are a valued client or subscriber.",
  },
  {
    id: "business-newsletter-orange",
    name: "Business Newsletter — Orange",
    tagline: "Bold newsletters for contractors and trucking professionals",
    contentType: "announcement",
    icon: Mail,
    thumbnailBg: "#FF6600",
    category: "newsletter",
    format: "660 × 1500 px",
    colors: ["#FF6600", "#1A1A1A", "#FFFFFF", "#FFF3E0"],
    vertical: ["contractors", "trucking"],
    canvaUrl: "https://www.canva.com/templates/EAGWT13iRvI-orange-and-black-modern-business-company-email-newsletter/",
    thumbnailUrl: "https://marketplace.canva.com/EAGWT13iRvI/1/0/566w/canva-orange-and-black-modern-business-company-email-newsletter-E_F3ZYEzQ_s.jpg",
    prompt: "Create a bold, high-energy business newsletter for contractors, trucking companies, and trade industries. Emphasize reliability, industry insights, and safety compliance updates. Bold orange design conveys energy and professionalism.",
    title: "Industry Update — Built for the Trades",
    bullets: [
      "OSHA compliance updates affecting contractor operations",
      "DOT safety rating changes and what they mean for fleets",
      "New carrier markets for hard-to-place contractor risks",
      "Workers comp audit season — what you need to know",
    ],
    cta: "Read Full Update",
    disclaimer: "You are receiving this because you are a valued client or subscriber.",
  },

  // --- PRESENTATIONS ---
  {
    id: "networking-presentation-vibrant",
    name: "Networking Presentation — Vibrant",
    tagline: "Train your team on the power of networking",
    contentType: "educational",
    icon: BarChart3,
    thumbnailBg: "#0D0D0D",
    category: "presentation",
    format: "1920 × 1080 px (10 slides)",
    colors: ["#0D0D0D", "#00FF88", "#FFD700", "#FFFFFF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAGP5udjG-M-black-vibrant-the-power-of-networking-presentation/",
    thumbnailUrl: "https://marketplace.canva.com/EAGP5udjG-M/1/0/400w/canva-black-vibrant-the-power-of-networking-presentation-FGNOU11Ul4k.jpg",
    prompt: "Create a vibrant, engaging presentation on the power of professional networking for insurance agents and financial advisors. Include networking statistics, actionable tips, relationship-building strategies, and a motivating call to action.",
    title: "The Power of Networking — Unlocking Opportunities",
    bullets: [
      "85% of jobs and deals are filled through networking, not ads",
      "Your network is your most valuable business asset",
      "Strategic relationships create referrals that compound over time",
      "AURA Connect gives you the tools to network smarter",
    ],
    cta: "Start Building Your Network Today",
    disclaimer: "",
  },
  {
    id: "referral-program-presentation",
    name: "Referral Program Presentation",
    tagline: "Launch a referral program your team will actually use",
    contentType: "educational",
    icon: Gift,
    thumbnailBg: "#0D0D0D",
    category: "presentation",
    format: "1920 × 1080 px (12 slides)",
    colors: ["#00E676", "#1565C0", "#FFFFFF", "#0D0D0D"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAFl8s01XbA-neon-green-blue-illustrated-employee-referral-program-company-presentation/",
    thumbnailUrl: "https://marketplace.canva.com/EAFl8s01XbA/1/0/400w/canva-neon-green-blue-illustrated-employee-referral-program-company-presentation-eF_ruQsJQ8k.jpg",
    prompt: "Create an engaging presentation to introduce a client or employee referral program. Cover how it works, the rewards structure, step-by-step how to refer, and FAQs. Tone should be energetic and motivating.",
    title: "Introducing Our Referral Program",
    bullets: [
      "Earn rewards for every successful referral you send our way",
      "Simple 3-step process: refer, we connect, you get rewarded",
      "No limits — refer as many people as you want",
      "Referral bonuses paid within 30 days of policy bind",
    ],
    cta: "Make Your First Referral Today",
    disclaimer: "Referral program terms and conditions apply.",
  },
  {
    id: "networking-presentation-blue",
    name: "Business Networking Presentation — Blue",
    tagline: "Professional networking deck for client workshops",
    contentType: "educational",
    icon: BarChart3,
    thumbnailBg: "#1A3E7A",
    category: "presentation",
    format: "1920 × 1080 px (10 slides)",
    colors: ["#1A3E7A", "#4A90D9", "#FFFFFF", "#EBF4FF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAG22B98pP4-blue-and-white-modern-business-networking-presentation/",
    thumbnailUrl: "https://marketplace.canva.com/EAG22B98pP4/1/0/400w/canva-blue-and-white-modern-business-networking-presentation-woRbJrdixWY.jpg",
    prompt: "Create a professional corporate presentation on business networking best practices. Cover the benefits of networking, how to build a strong professional network, online vs. in-person strategies, and how to leverage your CRM for relationship management.",
    title: "Business Networking — Your Competitive Advantage",
    bullets: [
      "Why strategic networking outperforms cold outreach every time",
      "Building your network: online, events, and referrals",
      "How to maintain relationships that compound over years",
      "Using your CRM to turn connections into revenue",
    ],
    cta: "Let's Grow Together",
    disclaimer: "",
  },

  // --- SOCIAL POSTS (Facebook / LinkedIn) ---
  {
    id: "networking-event-facebook",
    name: "Networking Event — Facebook Post",
    tagline: "Drive event registrations on Facebook",
    contentType: "event",
    icon: Users,
    thumbnailBg: "#1A1A1A",
    category: "facebook",
    format: "940 × 788 px",
    colors: ["#1A1A1A", "#F5F0E8", "#6B5B45", "#FFFFFF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAFYoVu1-zw-black-and-cream-simple-corporate-networking-event-facebook-post/",
    thumbnailUrl: "https://marketplace.canva.com/EAFYoVu1-zw/1/0/400w/canva-black-and-cream-simple-corporate-networking-event-facebook-post-5ihszQwbr08.jpg",
    prompt: "Create a Facebook post announcing a professional networking event for insurance agents, financial advisors, and business professionals. Include event details (date, time, venue placeholder), why attendees should come, and a clear RSVP call to action.",
    title: "You're Invited — Professional Networking Event",
    bullets: [
      "Meet local business owners, advisors, and decision-makers",
      "Complimentary refreshments and valuable connections",
      "Learn about new opportunities in your industry",
      "Limited seats — register before it fills up",
    ],
    cta: "RSVP to Secure Your Spot",
    disclaimer: "Event details subject to change.",
  },
  {
    id: "networking-event-linkedin",
    name: "Networking Event — LinkedIn Post",
    tagline: "Announce events to your professional network",
    contentType: "event",
    icon: Users,
    thumbnailBg: "#1A3E7A",
    category: "linkedin",
    format: "1200 × 627 px",
    colors: ["#1A3E7A", "#F5A623", "#FFFFFF", "#E8F0FE"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAG22B98pP4-blue-and-yellow-modern-business-network-event-linkedin-post/",
    thumbnailUrl: "https://marketplace.canva.com/EAG22B98pP4/1/0/400w/canva-blue-and-yellow-modern-business-network-event-linkedin-post-woRbJrdixWY.jpg",
    prompt: "Create a LinkedIn post announcing a professional networking event or industry conference. Highlight the value of attending, key speakers or topics, and include event details with a registration CTA.",
    title: "Professional Networking Event — Join Us",
    bullets: [
      "Connect with industry leaders and build lasting relationships",
      "Insights from top producers and financial professionals",
      "Structured networking sessions and open mixers",
      "Bring business cards — leave with new opportunities",
    ],
    cta: "Register on LinkedIn",
    disclaimer: "Event details subject to change.",
  },

  // --- POSTER ---
  {
    id: "networking-event-poster",
    name: "Networking Event Poster",
    tagline: "Post it, mail it, or share it digitally",
    contentType: "event",
    icon: Calendar,
    thumbnailBg: "#1A1A1A",
    category: "poster",
    format: "8.5 × 11 in",
    colors: ["#1A1A1A", "#F5F0E8", "#8B7355", "#FFFFFF"],
    vertical: null,
    canvaUrl: "https://www.canva.com/templates/EAFYobHjXAU-black-and-cream-simple-corporate-networking-event-poster/",
    thumbnailUrl: "https://marketplace.canva.com/EAFYobHjXAU/1/0/566w/canva-black-and-cream-simple-corporate-networking-event-poster-5y2fV9H65Tw.jpg",
    prompt: "Create an elegant corporate networking event poster for insurance agents, financial advisors, and contractors. Include event name, date/time/location placeholder, a grid of professional headshots, and RSVP details.",
    title: "Corporate Networking Event",
    bullets: [
      "An exclusive evening for professionals in financial services",
      "Meet industry leaders and build your referral network",
      "Featured speakers and open networking reception",
      "Cocktail attire — limited capacity event",
    ],
    cta: "RSVP by [Date]",
    disclaimer: "Event details subject to change. Space is limited.",
  },
];
