import { useEffect, useRef, useState } from "react";
import { Loader2, AlertCircle } from "lucide-react";

// Adobe PDF Embed API client IDs per domain
const ADOBE_CLIENT_IDS: Record<string, string> = {
  "doug-shane.lovable.app": "82d00c65432249999e0daa589ea94dfd",
  "id-preview--002628bd-9af2-4bd3-bfc6-c0546eed53c2.lovable.app": "0e4142db962d4d64b1fee6bf34bc67ac",
  "002628bd-9af2-4bd3-bfc6-c0546eed53c2.lovableproject.com": "f5d0868e6dbf4ee79ef0a26e2157776a",
  "localhost": "600cf411cda548c1ae0978f2b7a685f9",
};

function getAdobeClientId(): string {
  const hostname = window.location.hostname;
  return ADOBE_CLIENT_IDS[hostname] ?? ADOBE_CLIENT_IDS["localhost"];
}

export interface FillablePdfViewerProps {
  /**
   * Pre-filled PDF bytes. Generated by the parent using pdf-lib (AcroForm)
   * or raw bytes from the fillable PDF path. When this changes the viewer re-mounts.
   */
  pdfBytes: Uint8Array | null;
  /** True while the parent is generating the PDF — shows a loading spinner */
  isGenerating?: boolean;
  /** Display name for the PDF tab title */
  fileName?: string;
  /** Called when the user edits a field inside the Adobe PDF viewer */
  onFieldChange?: (fieldName: string, value: string) => void;
  /**
   * Called with the latest saved PDF bytes (from Adobe's SAVE_API).
   * Use this to power "Download Final PDF" with all in-viewer edits included.
   */
  onSaveBytes?: (bytes: Uint8Array) => void;
}

declare global {
  interface Window {
    AdobeDC?: any;
  }
}

function loadAdobeScript(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (window.AdobeDC) { resolve(); return; }
    const existing = document.getElementById("adobe-dc-view-sdk");
    if (existing) {
      existing.addEventListener("load", () => resolve());
      existing.addEventListener("error", reject);
      return;
    }
    const script = document.createElement("script");
    script.id = "adobe-dc-view-sdk";
    script.src = "https://acrobatservices.adobe.com/view-sdk/viewer.js";
    script.onload = () => resolve();
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

let viewerInstanceCounter = 0;

export default function FillablePdfViewer({
  pdfBytes,
  isGenerating = false,
  fileName = "ACORD Form.pdf",
  onFieldChange,
  onSaveBytes,
}: FillablePdfViewerProps) {
  const [viewerKey, setViewerKey] = useState(() => ++viewerInstanceCounter);
  const [adobeError, setAdobeError] = useState<string | null>(null);
  const [adobeLoading, setAdobeLoading] = useState(false);
  const divId = `adobe-pdf-viewer-${viewerKey}`;
  const cancelledRef = useRef(false);
  const onFieldChangeRef = useRef(onFieldChange);
  onFieldChangeRef.current = onFieldChange;
  const onSaveBytesRef = useRef(onSaveBytes);
  onSaveBytesRef.current = onSaveBytes;

  // Bump the viewer key whenever pdfBytes reference changes (new generation)
  const prevBytesRef = useRef<Uint8Array | null>(null);
  useEffect(() => {
    if (pdfBytes && pdfBytes !== prevBytesRef.current) {
      prevBytesRef.current = pdfBytes;
      setViewerKey(++viewerInstanceCounter);
    }
  }, [pdfBytes]);

  useEffect(() => {
    if (!pdfBytes) return;

    cancelledRef.current = false;
    setAdobeError(null);
    setAdobeLoading(true);

    async function initViewer() {
      try {
        await loadAdobeScript();

        await new Promise<void>((resolve) => {
          if (window.AdobeDC) { resolve(); return; }
          document.addEventListener("adobe_dc_view_sdk.ready", () => resolve(), { once: true });
        });

        if (cancelledRef.current) return;

        // Wait for the div to actually be present in the DOM before Adobe tries to use it
        await new Promise<void>((resolve) => {
          const check = () => {
            if (document.getElementById(divId)) { resolve(); return; }
            requestAnimationFrame(check);
          };
          check();
        });

        if (cancelledRef.current) return;

        const view = new window.AdobeDC.View({
          clientId: getAdobeClientId(),
          divId,
        });

        // ── SAVE_API: capture bytes whenever Adobe auto-saves or user triggers save ──
        // This gives us the live edited bytes (including in-viewer edits) for download.
        view.registerCallback(
          window.AdobeDC.View.Enum.CallbackType.SAVE_API,
          (metaData: any, content: ArrayBuffer) => {
            if (!cancelledRef.current && onSaveBytesRef.current) {
              onSaveBytesRef.current(new Uint8Array(content));
            }
            return new Promise((resolve) => {
              resolve({ code: window.AdobeDC.View.Enum.ApiResponseCode.SUCCESS });
            });
          },
          {
            autoSaveFrequency: 0,     // only save on explicit trigger
            enableFocusPolling: true, // save when user clicks away from a field
            showSaveButton: false,    // hide Adobe's own save button
          }
        );

        // ── EVENT_LISTENER: sync field edits back to the left panel in real-time ──
        view.registerCallback(
          window.AdobeDC.View.Enum.CallbackType.EVENT_LISTENER,
          (event: any) => {
            if (cancelledRef.current) return;
            if (event.type === "FORM_FIELD_CHANGED") {
              // Adobe puts field info under event.data.fieldData OR event.data directly
              const fieldData = event.data?.fieldData || event.data || {};
              const name = fieldData.name ?? event.data?.name;
              const value = fieldData.value ?? event.data?.value ?? "";
              if (name && onFieldChangeRef.current) {
                onFieldChangeRef.current(name, String(value));
              }
            }
          },
          { enablePDFAnalytics: true, listenOn: ["FORM_FIELD_CHANGED"] }
        );

        // Build a clean ArrayBuffer from the Uint8Array (avoids SharedArrayBuffer issues)
        const pdfBuffer = pdfBytes.buffer.slice(
          pdfBytes.byteOffset,
          pdfBytes.byteOffset + pdfBytes.byteLength
        ) as ArrayBuffer;

        // FULL_WINDOW is the only mode that supports interactive form filling
        // IN_LINE mode does not support form editing per Adobe docs
        await view.previewFile(
          {
            content: { promise: Promise.resolve(pdfBuffer) },
            metaData: { fileName },
          },
          {
            embedMode: "FULL_WINDOW",
            enableFormFilling: true,
            showAnnotationTools: false,
            showLeftHandPanel: false,
            showThumbnails: false,
            showBookmarks: false,
            showDownloadPDF: true,
            showPrintPDF: true,
            defaultViewMode: "FIT_WIDTH",
          }
        );

        if (!cancelledRef.current) setAdobeLoading(false);
      } catch (err: any) {
        if (!cancelledRef.current) {
          console.error("Adobe PDF Embed error:", err);
          setAdobeError(err?.message || "Failed to initialize PDF viewer");
          setAdobeLoading(false);
        }
      }
    }

    initViewer();

    return () => {
      cancelledRef.current = true;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewerKey]);

  const showSpinner = isGenerating || (adobeLoading && !adobeError);

  return (
    // FULL_WINDOW mode needs a fixed-height container — it fills 100% of parent height/width
    <div className="flex flex-col relative bg-muted/20" style={{ height: "100%", minHeight: "600px" }}>
      {/* Loading overlay */}
      {showSpinner && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-muted-foreground z-10 bg-background/80">
          <Loader2 className="h-6 w-6 animate-spin text-primary" />
          <span className="text-sm font-medium">
            {isGenerating ? "Preparing fillable PDF…" : "Loading viewer…"}
          </span>
        </div>
      )}

      {/* Error state */}
      {adobeError && !showSpinner && (
        <div className="flex flex-col items-center justify-center h-full gap-3 text-muted-foreground p-8 text-center">
          <AlertCircle className="h-8 w-8 text-destructive" />
          <p className="text-sm font-medium">PDF viewer error</p>
          <p className="text-xs text-destructive max-w-sm">{adobeError}</p>
          <p className="text-xs text-muted-foreground mt-1">
            Domain: <code className="bg-muted px-1 rounded">{window.location.hostname}</code>
          </p>
        </div>
      )}

      {/* Waiting for bytes */}
      {!pdfBytes && !isGenerating && !adobeError && (
        <div className="flex flex-col items-center justify-center h-full gap-3 text-muted-foreground p-8 text-center">
          <Loader2 className="h-6 w-6 text-muted-foreground animate-spin" />
          <p className="text-sm">Loading PDF…</p>
        </div>
      )}

      {/* Adobe renders into this div — FULL_WINDOW fills parent height */}
      <div
        key={viewerKey}
        id={divId}
        style={{ width: "100%", height: "100%", minHeight: "600px" }}
      />
    </div>
  );
}
